name: simple test site
version: 1.0
appVersion: latest
description: Simple pippo static web site.
keywords:
- website
- pippo
sources:
- https://github.com/carlodeba/carlodeba
maintainers:
- name: carlodeba
