name: phpmyadmin-server
version: 1.0
appVersion: latest
description: Phpmyadmin standalone server.
keywords:
- phpmyadmin
- mysql
sources:
- https://github.com/carlodeba/phpmyadmin
maintainers:
- name: carlodeba
