apiVersion: v1
kind: Service
metadata:
  name: {{ template "carlodeba.fullname" . }}
  labels:
    app: {{ template "carlodeba.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ template "carlodeba.fullname" . }}

